global using System.Linq.Expressions;
global using Booker.Models.Enums;
global using Booker.Repository.Entities;
global using Booker.Repository.Repositories.Interfaces;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.DependencyInjection;
