<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Booker.Models\Booker.Models.csproj" />
    <ProjectReference Include="..\..\src\Booker.Repository\Booker.Repository.csproj" />
    <ProjectReference Include="..\..\src\Booker.Services\Booker.Services.csproj" />
  </ItemGroup>

</Project>